export const SYMBOLS = {
    Adapter: Symbol.for('Adapter'),
    Initializer: Symbol.for('Initializer'),
    RunInfoLoader: Symbol.for('RunInfoLoader'),
    ShardHandler: Symbol.for('ShardHandler'),
    TestRunCreator: Symbol.for('TestRunCreator'),
    TestRunner: Symbol.for('TestRunner'),
    BrowserManager: Symbol.for('BrowserManager'),
    WebServerManager: Symbol.for('WebServerManager'),
    BatchHandler: Symbol.for('BatchHandler'),
    BatchHandlerFactory: Symbol.for('BatchHandlerFactory'),
    TestExecutionReporter: Symbol.for('TestExecutionReporter'),
    TestEventHandler: Symbol.for('TestEventHandler'),
    TestEventHandlerFactory: Symbol.for('TestEventHandlerFactory'),
    RunContext: Symbol.for('RunContext'),
} as const;
