services:
    dynamodb-local:
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -cors http://localhost:8001'
        restart: always
        image: 'amazon/dynamodb-local:latest'
        container_name: dynamodb-local
        ports:
            - '8000:8000'
        volumes:
            - './db:/home/dynamodblocal/data'
        working_dir: /home/dynamodblocal

    adminer-dynamo:
        image: taydy/dynamodb-manager
        restart: always
        privileged: true
        ports:
            - 8001:80

    test:
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
        restart: always
        image: 'amazon/dynamodb-local:latest'
        container_name: dynamodb-local-test
        ports:
            - '8002:8000'
        profiles:
            - test
        tmpfs:
            - /home/dynamodblocal/data

        working_dir: /home/dynamodblocal
