import { loadPlugins } from '../helpers/plugin.js';
import { withErrorHandling } from './error-handler.js';
import { program } from './program.js';

export default async () => {
    const command = program.command('create-report').description('Create for selected storage type.');

    for await (const { factory, subCommand } of loadPlugins(command)) {
        subCommand
            .option('--run-id <string>', 'Run id generated by create command')
            .option('--reporter <string>', 'Reporter type', 'json')
            .action(
                withErrorHandling(async (options) => {
                    const adapter = await factory(options);
                    console.log(JSON.stringify(await adapter.getReportData(options.runId)));
                    await adapter.dispose();
                }),
            );
    }
};
