import { loadPlugins } from '../helpers/plugin.js';
import { CliTestRunner } from '../runners/cli-test-runner.js';
import { withErrorHandling } from './error-handler.js';
import { program } from './program.js';
import { createContainer, SYMBOLS } from '../container.js';
import { TestRunner } from '../types/test-runner.js';
import { TestServerRunner } from '../runners/test-server-runner.js';

export default async () => {
    const command = program.command('run').description('Start test run shard');

    for await (const { register, subCommand } of loadPlugins(command)) {
        subCommand
            .requiredOption('--run-id <string>', 'Run id generated by create command')
            .option(
                '-o, --output <string>',
                'Output folder for blob reports. Existing content is deleted before writing the new report.',
                'blob-reports',
            )
            .action(
                withErrorHandling(async (options) => {
                    const container = createContainer();
                    await register(container, options);
                    container.bind<string>(SYMBOLS.RunId).toConstantValue(options.runId);
                    container.bind<string>(SYMBOLS.OutputFolder).toConstantValue(options.output);
                    container.bind<TestRunner>(SYMBOLS.TestRunner).to(TestServerRunner).inSingletonScope();
                    const runner = container.get<TestRunner>(SYMBOLS.TestRunner);
                    try {
                        await runner.runTests();
                        console.log('Run completed');
                    } finally {
                        await container.unbindAllAsync();
                    }
                }),
            );
    }
};
