import { loadPlugins } from '../plugin';
import { TestRunner } from '../test-runner';
import { withErrorHandling } from './error-handler';
import { program } from './program';

const command = program.command('run').description('Start test run shard');

for (const { factory, subCommand } of loadPlugins(command)) {
    subCommand
        .requiredOption('--run-id <string>', 'Run id generated by create command')
        .option(
            '-o, --output <string>',
            'Output folder for blob reports. Existing content is deleted before writing the new report.',
            'blob-reports',
        )
        .action(
            withErrorHandling(async (options) => {
                const adapter = factory(options);
                const runner = new TestRunner(options as any, adapter);
                await runner.runTests();
                console.log('Run completed');
            }),
        );
}
