services:
    mysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test

    test:
        image: mysql
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
        profiles:
            - test
        healthcheck:
            test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-ppassword"]
            interval: 10s
            retries: 10
            timeout: 10s
            start_period: 20s