name: Setup e2e Test Environment
description: Basic setup for e2e tests

inputs:
  install-browser:
    description: "Install Playwright browsers"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build lib
      shell: bash
      run: |
        pnpm build
        pnpm install --offline

    - name: Get Playwright version
      shell: bash
      id: version
      run: |
        echo ${{ inputs.install-browser }}
        PLAYWRIGHT_VERSION=$(node -p "require('./node_modules/@playwright/test/package.json').version")
        echo "PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}" >> $GITHUB_OUTPUT

    - name: Cache Playwright
      if: ${{ inputs.install-browser == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.version.outputs.PLAYWRIGHT_VERSION }}

    - name: Install Playwright browsers
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' && inputs.install-browser == 'true' }}
      run: pnpm exec playwright install --with-deps
