name: Setup e2e Test Environment
description: Basic setup for e2e tests

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Install Playwright browsers
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
