name: Pull Request Checks

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: link packages
              run: |
                  npm run link-packages

            - name: Instal podman
              run: |
                  sudo apt-get update
                  sudo apt-get install -y podman podman-compose
                  systemctl --user start podman.socket
                  systemctl --user enable podman.socket
                  export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
                  # Verify podman is working
                  podman info
                  # Set compose to use podman
                  export COMPOSE_PROVIDER=podman

            - name: Run tests
              run: npm test -- --poolOptions.threads.singleThread true
